### ISSUE TITLE
[Sprint] Detection head re-implementation for PyNetsPresso compatibility

### ISSUE THREAD

**Issue by illian01** [Nota-NetsPresso/netspresso-trainer#177]
## Description

- Present NetsPresso Trainer detection model can't pass `train -> compression -> retrain -> benchmark` process because PyNetsPresso can't compress present detection head.
- In this sprint, the detection head will be re-implemented, and tested by passing `train -> compression -> retrain -> benchmark` process.

### Common
- [x] I would create a corresponding branch for this issue from the designated (mostly `dev`) branch.
- [x] This issue only contains a preceding agreement between project owners.

### TODO
- [x] Detection training with various backbone should succeed.
- [x] NP Compressor with trained fx checkpoint should succeed.
- [ ] NP Launcher with trained onnx checkpoint should succeed.

**Comment by illian01** [comment]
WIP in #184

**Comment by illian01** [comment]
#194
To complete this issue, we have to solve these issues.
- Present model has separated backbone and head. To integrate them, compressor should support `torch.meshgrid` or trainer find work around.
- Present model can't be converted to TensorRT. `NonZero` operation of onnx not supported by converter's TensorRT version. May need TensorRT update or work around.

**Comment by illian01** [comment]
We decided followings through internal discussion:
- Leave 2-stage detector to support only training, compression (backbone), and fx retraining.
- We don't support TensorRT for 2-stage detector now, because this has limitation by TensorRT version.

Thus, this issue will be closed after refactoring 2-stage detector, and re-open when we need TensorRT of the model.
