### ISSUE TITLE
[Sprint] Support augmentation for classification task: cutmix, mixup

### ISSUE THREAD

**Issue by illian01** [Nota-NetsPresso/netspresso-trainer#215]
## Description

- Add augmentation technique `cutmix` and `mixup`

## Checklists

- [x] I would create a corresponding branch for this issue from the designated (mostly `dev`) branch.
- [x] This issue only contains a preceding agreement between project owners.

## Todo

- [x] Enable `cutmix` on classification task
- [x] Enable `mixup` on classification task
